# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 99edac901f08d7a9c52997389681a4cf5f204162aac42057e34054819d7113949ca7733906fc6b9be549f3e79f9fb003a4bec5fabea827bc9c632c4947d16237

test:
  secret_key_base: fb5efe9e4670f9196bb2f136b54d53f79143cdff52f017d086ead13e3b73ca15559049ad9caaa0eb30c1adb480675b0e4a572f4d53273a4938561a1caea87505

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
